name: Kernel Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential cpio curl flex git \
          kmod libssl-dev libncurses5-dev libelf-dev \
          python3 unzip wget xz-utils

    - name: Clone Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang proton-clang

    - name: Restore missing touchscreen blob headers
      run: |
        wget https://github.com/pjgowtham/android_kernel_oneplus_sm8350/raw/lineage-22.2/drivers/input/touchscreen/oplus_touchscreen_v2/Focal/ft3681/FT3681_Cal_Test_app.i -O drivers/input/touchscreen/oplus_touchscreen_v2/Focal/ft3681/FT3681_Cal_Test_app.i
        wget https://github.com/pjgowtham/android_kernel_oneplus_sm8350/raw/lineage-22.2/drivers/input/touchscreen/oplus_touchscreen_v2/Focal/ft3681/FT3681_Pramboot_V1.3_20211109.i -O drivers/input/touchscreen/oplus_touchscreen_v2/Focal/ft3681/FT3681_Pramboot_V1.3_20211109.i    

    - name: Generate defconfig (use system GCC for host tools)
      run: |
        make O=out ARCH=arm64 SUBARCH=arm64 realme_defconfig

    - name: Build kernel with Proton Clang
      run: |
        echo "PATH=$GITHUB_WORKSPACE/proton-clang/bin:$PATH" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        make -j$(nproc) O=out \
          ARCH=arm64 \
          SUBARCH=arm64 \
          CC=$GITHUB_WORKSPACE/proton-clang/bin/clang \
          CROSS_COMPILE=$GITHUB_WORKSPACE/proton-clang/bin/aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/proton-clang/bin/arm-linux-gnueabi- \
          CLANG_TRIPLE=$GITHUB_WORKSPACE/proton-clang/bin/aarch64-linux-gnu- \
          AR=$GITHUB_WORKSPACE/proton-clang/bin/llvm-ar \
          NM=$GITHUB_WORKSPACE/proton-clang/bin/llvm-nm \
          OBJCOPY=$GITHUB_WORKSPACE/proton-clang/bin/llvm-objcopy \
          OBJDUMP=$GITHUB_WORKSPACE/proton-clang/bin/llvm-objdump \
          STRIP=$GITHUB_WORKSPACE/proton-clang/bin/llvm-strip \
          LD=$GITHUB_WORKSPACE/proton-clang/bin/ld.lld

    - name: Install kernel modules
      run: |
        mkdir -p modules_tmp
          ARCH=arm64 \
          SUBARCH=arm64 \
          CC=$GITHUB_WORKSPACE/proton-clang/bin/clang \
          CROSS_COMPILE=$GITHUB_WORKSPACE/proton-clang/bin/aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/proton-clang/bin/arm-linux-gnueabi- \
          CLANG_TRIPLE=$GITHUB_WORKSPACE/proton-clang/bin/aarch64-linux-gnu- \
          AR=$GITHUB_WORKSPACE/proton-clang/bin/llvm-ar \
          NM=$GITHUB_WORKSPACE/proton-clang/bin/llvm-nm \
          OBJCOPY=$GITHUB_WORKSPACE/proton-clang/bin/llvm-objcopy \
          OBJDUMP=$GITHUB_WORKSPACE/proton-clang/bin/llvm-objdump \
          STRIP=$GITHUB_WORKSPACE/proton-clang/bin/llvm-strip \
          LD=$GITHUB_WORKSPACE/proton-clang/bin/ld.lld
        make O=out INSTALL_MOD_PATH=$PWD/modules_tmp modules_install

        # Flatten .ko files and strip only ELF-valid ones
        mkdir -p flat_ko
        find modules_tmp/lib/modules/ -name "*.ko" | while read -r module; do
          if file "$module" | grep -q "ELF"; then
            $GITHUB_WORKSPACE/proton-clang/bin/llvm-strip --strip-unneeded "$module"
          fi
          cp "$module" flat_ko/
        done

    - name: Prepare AnyKernel3 directory
      run: |
        git clone --depth=1 https://github.com/Saikatsaha1996/AnyKernel3 anykernel3
        mkdir -p anykernel3/modules/vendor/lib/modules
        mkdir -p anykernel3/modules/vendor_dlkm/lib/modules

        # Copy flattened modules
        cp -av flat_ko/*.ko anykernel3/modules/vendor/lib/modules/
        cp -av flat_ko/*.ko anykernel3/modules/vendor_dlkm/lib/modules/

        # Find and copy metadata (modules.dep and modules.order)
        find modules_tmp/lib/modules/ -name "modules.dep" -exec cp {} anykernel3/modules/vendor/lib/modules/ \;
        find modules_tmp/lib/modules/ -name "modules.order" -exec cp {} anykernel3/modules/vendor/lib/modules/ \;

        cp anykernel3/modules/vendor/lib/modules/modules.dep anykernel3/modules/vendor_dlkm/lib/modules/
        cp anykernel3/modules/vendor/lib/modules/modules.order anykernel3/modules/vendor_dlkm/lib/modules/
    - name: Copy kernel, dtb to AnyKernel3
      run: |
        cp out/arch/arm64/boot/Image anykernel3/
        find out/arch/arm64/boot/dts/vendor/oplus/porsche/ -name "*.dtb" -exec cat {} + > anykernel3/dtb

    - name: Create dtbo.img
      run: |
       mkdir -p dtbo_output
       find out/arch/arm64/boot/dts/vendor/oplus/porsche/ -name "*.dtbo" -exec cp {} dtbo_output/ \;
       mkdir -p tools/ufdt/utils/src/
       curl -Lo tools/ufdt/utils/src/mkdtboimg.py https://android.googlesource.com/platform/system/libufdt/+/refs/heads/master/utils/src/mkdtboimg.py?format=TEXT
       base64 -d tools/ufdt/utils/src/mkdtboimg.py > tools/ufdt/utils/src/mkdtboimg_decoded.py
       chmod +x tools/ufdt/utils/src/mkdtboimg_decoded.py
       python3 tools/ufdt/utils/src/mkdtboimg_decoded.py create dtbo.img --page_size 4096 dtbo_output/*.dtbo
       mv dtbo.img anykernel3/
        
    - name: Create flashable ZIP
      run: |
        cd anykernel3
        zip -r9 kernel-porsche.zip * -x .git README.md *placeholder

    - name: Upload AnyKernel3 ZIP
      uses: actions/upload-artifact@v4
      with:
       name: Flashable-ZIP
       path: anykernel3/kernel-porsche.zip

    - name: Cleanup extra files
      run: |
        rm -rf modules_tmp dtbo_output tools mkdtboimg.py
