name: Kernel Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential cpio curl flex git kmod \
          libssl-dev libncurses5-dev libelf-dev python3 \
          unzip wget xz-utils

    - name: Clone Proton Clang toolchain
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Build kernel
      run: |
        export PATH="$PWD/clang/bin:$PATH"
        export ARCH=arm64
        export SUBARCH=arm64

        # Step 1: Build config and host tools (no CC override here)
        make O=out realme_defconfig

        # Step 2: Build kernel with Clang
        make -j$(nproc) O=out \
          CC=clang \
          LD=ld.lld \
          AR=llvm-ar \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CLANG_TRIPLE=aarch64-linux-gnu-

    - name: Upload kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Kernel
        path: out/arch/arm64/boot/Image
